### ISSUE TITLE
can't import index.css in app.jsx file

### ISSUE THREAD

**Issue by ishita0909** [adrianhajdin/project_medical_pager_chat#37]
ERROR in ./src/App.jsx 10:0-46 Module not found: Error: Can't resolve 'stream-chat-react/dist/css/index.css' in 'C:\Users\ashok\OneDrive\Desktop\Chat Application\client\src'

**Comment by kash-1308** [comment]
> ERROR in ./src/App.jsx 10:0-46 Module not found: Error: Can't resolve 'stream-chat-react/dist/css/index.css' in 'C:\Users\ashok\OneDrive\Desktop\Chat Application\client\src'
please can you tell me how you resolved this issue as my problem showing in my case
